// Javascript
import 'jquery/src/jquery';
import 'bootstrap';
import 'cookieconsent';
import 'slick-carousel';
import 'classlist-polyfill';
import './lib/validity-polyfill';
import './lib/form-functions';
import './lib/dom';
